export type TokenType =
  | "number"
  | "bigint"
  | "string"
  | "regex"
  | "null"
  | "undefined"
  | "EndOfFile"
  | ";"
  | "{"
  | "}"
  | "["
  | "]"
  | "("
  | ")"
  | "."
  | ","
  | ":"
  | "#"
  | "|"
  | "&"
  | "^"
  | "=>"
  | "&&"
  | "?."
  | "LogicalOrAndNullishCoalescing"
  | "function"
  | "function*"
  | "yield"
  | "async"
  | "await"
  | "return"
  | "if"
  | "else"
  | "of"
  | "for"
  | "while"
  | "do"
  | "continue"
  | "this"
  | "throw"
  | "try"
  | "catch"
  | "finally"
  | "SquareBrackets"
  | "UnaryOperator"
  | "AdditiveOperator"
  | "MultiplicativeOperator"
  | "PowerOperator"
  | "AssignmentOperator"
  | "ComparisonOperator"
  | "EqualityOperator"
  | "ComplexAssignmentOperator"
  | "Identifier"
  | "VariableDeclaration"
  | "boolean"
  | "class"
  | "extends"
  | "static"
  | "new"
  | null;

export interface Token {
  type: TokenType;
  value: string;
}

export type ASTNodeType =
  | "NumericLiteral"
  | "BigintLiteral"
  | "StringLiteral"
  | "BooleanLiteral"
  | "NullLiteral"
  | "UndefinedLiteral"
  | "ArrayLiteral"
  | "ObjectLiteral"
  | "RegExpLiteral"
  | "Property"
  | "BlockStatement"
  | "ForStatement"
  | "ForOfStatement"
  | "WhileStatement"
  | "DoWhileStatement"
  | "ReturnStatement"
  | "ContinueStatement"
  | "ThrowStatement"
  | "TryStatement"
  | "CatchClause"
  | "BinaryExpression"
  | "UnaryExpression"
  | "ParenthesizedExpression"
  | "AssignmentExpression"
  | "ComplexAssignmentExpression"
  | "MemberExpression"
  | "AwaitExpression"
  | "YieldExpression"
  | "SequenceExpression"
  | "ArrowFunctionExpression"
  | "FunctionExpression"
  | "NewExpression"
  | "ThisExpression"
  | "LogicalExpression"
  | "OptionalMemberExpression"
  | "OptionalCallExpression"
  | "Identifier"
  | "VariableDeclaration"
  | "FunctionDeclaration"
  | "ClassDeclaration"
  | "ClassBody"
  | "ClassProperty"
  | "ClassPrivateProperty"
  | "ClassMethodDefinition"
  | "PrivateName"
  | "AssignmentPattern"
  | "CallExpression"
  | "IfStatement"
  | "CommentLine"
  | "CommentBlock"
  | "Program";

export type Operator =
  | "+"
  | "-"
  | "*"
  | "/"
  | "!"
  | "**"
  | "="
  | "+="
  | "-="
  | "*="
  | "/="
  | "<"
  | ">"
  | "<="
  | ">="
  | "=="
  | "!="
  | "==="
  | "!=="
  | "=>"
  | "&&"
  | "||"
  | "??"
  | "|"
  | "&"
  | "^"
  | "?.";

export interface ASTNode {
  type: ASTNodeType;
  value?: string | number | boolean | ASTNode | null | undefined;
  body?: (ASTNode | null)[] | ASTNode;
  operator?: Operator;
  left?: ASTNode;
  right?: ASTNode;
  name?: string;
  id?: ASTNode;
  object?: ASTNode;
  property?: ASTNode;
  condition?: ASTNode;
  params?: ASTNode[];
  generator?: boolean;
  async?: boolean;
  arguments?: ASTNode[];
  callee?: ASTNode;
  init?: ASTNode | null;
  test?: ASTNode | null;
  update?: ASTNode | null;
  kind?: "let" | "const" | "constructor" | "method";
  argument?: ASTNode;
  expressions?: ASTNode[];
  properties?: ASTNode[];
  key?: ASTNode;
  computed?: boolean;
  method?: boolean;
  elements?: ASTNode[];
  superClass?: ASTNode;
  static?: boolean;
  handler?: ASTNode;
  finalizer?: ASTNode;
  param?: ASTNode;
  block?: ASTNode;
  pattern?: string;
  flags?: string;
  optional?: boolean;
  consequent?: ASTNode;
  alternate?: ASTNode;
}
